import os
import smtplib
import zipfile
import importlib.util
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders


# ✅ Dynamic import for 102303412.py (filename starts with number)
spec = importlib.util.spec_from_file_location("mashup_module", "102303412.py")
mashup_module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mashup_module)

Mashup = mashup_module.Mashup


def process_mashup_request(singer, n, y, email, output_filename="mashup.mp3"):
    """
    Wrapper to run the mashup logic.
    """
    try:
        mashup = Mashup(singer, n, y, output_filename)
        mashup.run()

        if not os.path.exists(output_filename):
            raise FileNotFoundError("Output file was not generated.")

        return output_filename

    except Exception as e:
        raise RuntimeError(f"Processing failed: {str(e)}")


def create_zip(file_path, zip_name):
    """
    Compress the generated MP3 into a ZIP file.
    """
    with zipfile.ZipFile(zip_name, 'w', zipfile.ZIP_DEFLATED) as zipf:
        zipf.write(file_path, os.path.basename(file_path))

    return zip_name


def send_email(recipient, attachment_path):
    """
    Send an email with the zip attachment.
    Reads credentials from environment variables.
    """

    smtp_server = os.environ.get('MAIL_SERVER', 'smtp.gmail.com')
    smtp_port = int(os.environ.get('MAIL_PORT', 587))
    sender_email = os.environ.get('MAIL_EMAIL')
    sender_password = os.environ.get('MAIL_PASSWORD')

    if not sender_email or not sender_password:
        raise ValueError(
            "Email credentials not set in environment variables (MAIL_EMAIL, MAIL_PASSWORD)."
        )

    msg = MIMEMultipart()
    msg['From'] = sender_email
    msg['To'] = recipient
    msg['Subject'] = "Your Mashup is Ready! 🎵"

    body = "Here is the mashup you requested.\n\nGenerated by Mashup Web Service."
    msg.attach(MIMEText(body, 'plain'))

    # Attach ZIP file
    with open(attachment_path, "rb") as attachment:
        part = MIMEBase("application", "octet-stream")
        part.set_payload(attachment.read())

    encoders.encode_base64(part)

    part.add_header(
        "Content-Disposition",
        f"attachment; filename={os.path.basename(attachment_path)}",
    )

    msg.attach(part)

    try:
        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()
        server.login(sender_email, sender_password)
        server.sendmail(sender_email, recipient, msg.as_string())
        server.quit()

    except Exception as e:
        raise RuntimeError(f"Failed to send email: {str(e)}")


